### ISSUE TITLE
move more

### ISSUE THREAD

**Issue by yaming116** [rey5137/SlideLayout#1]
![https://lh4.googleusercontent.com/-eGUYZIIVtGE/UxaTARSOcEI/AAAAAAAAApo/AUDV-6Y8ktE/w360-h640/4+-+1](https://lh4.googleusercontent.com/-eGUYZIIVtGE/UxaTARSOcEI/AAAAAAAAApo/AUDV-6Y8ktE/w360-h640/4+-+1)

**Comment by rey5137** [comment]
Can you please give me more detail of this issue ? If you mean the content view is over-dragged, then it isn't an issue, but a feature. You can turn it off by setting "overDrag" attribute to false in SlideMenuStyle

**Comment by yaming116** [comment]
i see ,thx
