### ISSUE TITLE
Tweak in Right To Left SlideLayout (not issue)

### ISSUE THREAD

**Issue by nishanthsdei** [rey5137/SlideLayout#2]
Hello Rey Pham
I'm using your Slide layout library (https://github.com/rey5137/SlideLayout) and its working fine; I need to make a little tweak on this. While layout slide from right to left (openRightMenu function) the top layout is showing too much of the main screen. How can we reduce the visibility content of the main screen?
I really appreciate if you you help me on this. 

Thanks in Advance
Nishanth

**Comment by rey5137** [comment]
Hi Nishanth,

Do you want to change the visible width of the content view when the right menu is opened? If so, please find the correct SlideMenuStyle for right menu in styles.xml and modify the value of  "sm_menuBorder" 
- sm_menuBorder: The size of content view visible when menu opened, can be dimension or percent of content view's size 

Rey

**Comment by nishanthsdei** [comment]
Thanks Rey,
It worked perfectly, you are life saver. I have couple of queries. 

1) I like to slide my main layout only from right (right to left) but library slides to all four sides, To achieve this i disabled the gesture functionality for other three sides on library. Is this correct way or do you have any option to do this?.

2) I have multiple screens that slides in different direction so Is it possible to maintain that on one screen i slide from left to right and another from right to left.(by disabling other three sides)

Please help me on this

Thanks
Nishanth

**Comment by rey5137** [comment]
1) You can remove any menu by remove the view in layout xml file (make sure to remove the related menuChild attribute of SlideLayout view and update the correct index of another menuChild attribute. Ex: if you remove bottom menu view in layout file, you also have to remove "sl_bottomMenuChild" attribute)

2) For current version, you can disable the drag gesture of all menus by call function setDragEnable(boolean). I will update the code so you can enable /disable drag gesture for each menu separately if I have free time. Or may be you can do it yourself :)

Rey
